# Generated by Django 2.1.2 on 2018-11-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relic',
            name='district',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='relic',
            name='municipality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='relic',
            name='province',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
